sudo: false
language: php

# Cache some data across builds for performance.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

notifications:
  email:
    on_success: never
    #on_failure: change
    on_failure: never # just until things are working

branches:
  only:
    - master
    - 1.x

matrix:
  include:
    - php: 7.1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mysql --version
  - phpenv config-rm xdebug.ini
  - phpenv versions
  - php --version
  - composer install
  - nvm install stable
  - npm install
  - npm --version
  - node --version

script:
  - npm --version
  - npm run build
