sudo: false
language: php

dist: trusty

# Cache some data across builds for performance.
#cache:
#  apt: true
#  directories:
#    - node_modules
#    - vendor
#    # Cache directory for older Composer versions.
#    - $HOME/.composer/cache Bring
#    # Cache directory for more recent Composer versions.
#    - $HOME/.cache/composer/files

php:
  - 7.1

env:
  global:
    - LINT=1

notifications:
  email:
    on_success: never
    #on_failure: change
    on_failure: never # just until things are working

branches:
  only:
    - master
    - 1.x

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - npm i -g npm@6

install:
  - cd $TRAVIS_BUILD_DIR
  - composer install --no-suggest
  - npm install -g eslint
  - npm install || cat /home/travis/.npm/_logs/2018-12-07T18_57_40_130Z-debug.log

before_script:
  - phpenv rehash;

script:
  - npm test
