# Travis CI configuration
# @link https://travis-ci.org/

os: linux
dist: xenial

language: generic

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor
    - $HOME/.npm
    - $HOME/.nvm/.cache

branches:
  only:
    - stable
    - 2.x

before_install:
  - npm --version
  - node --version
  - nvm install --latest-npm

jobs:
  include:
    - name: Lint JS
      install: npm ci
      script: npm run lint:scripts

    - name: Lint CSS
      install: npm ci
      script: npm run lint:styles

    - name: Lint JSON
      install: npm ci
      script: npm run lint:pkg

    - name: Lint PHP
      install: composer install
      script:
        - find . \( -name '*.php' \) -not -path "./vendor/*" | xargs -n1 bash -c 'php -lf $0 || exit 1'
        - npm run lint:php

    - name: Build
      install:
        - npm ci
        - composer install
      script: npm run build
