name: Coding Standards

on:
  push:
    branches:
      - develop
      - stable
      - release/**
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Script and Style Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version-file: '.nvmrc'
            check-latest: true
            cache: npm

      - name: Npm install
        run: npm install

      - name: Lint JavaScript
        run: npm run lint:scripts

      - name: Lint Styles
        run: npm run lint:styles

      - name: Lint package.json
        run: npm run lint:pkg

  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            coverage: none
            tools: composer, cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
            composer-options: '--no-progress --no-ansi --no-interaction'

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Log PHPCS debug information
        run: phpcs -i

      - name: Run PHPCS
        run: phpcs -q -n --report=checkstyle . | cs2pr
